"""
Email service — sends transactional emails via Flask-Mail (SMTP).

All send_* functions are synchronous; they are intended to be called
from Celery task workers so the HTTP request thread is never blocked.

Calling convention:
    from app.services.email_service import send_verification_email
    send_verification_email(user_email, user_name, verify_url)

Flask-Mail is initialised in the app factory.  get_mail() fetches it
from current_app.extensions so there is no import-time initialisation.

Environment variables (set via config/settings.py):
    MAIL_SERVER          SMTP host (default: smtp.gmail.com)
    MAIL_PORT            587
    MAIL_USE_TLS         True
    MAIL_USERNAME        Sender address / login
    MAIL_PASSWORD        App password or SMTP password
    MAIL_DEFAULT_SENDER  "Hermes <noreply@hermes.in>" (fallback to MAIL_USERNAME)
"""
from __future__ import annotations

from flask import current_app
from flask_mail import Message

def get_mail():
    """Return the Flask-Mail instance attached to the current app."""
    mail = current_app.extensions.get("mail")
    if mail is None:
        raise RuntimeError("Flask-Mail is not initialized on this app.")
    return mail


# ---------------------------------------------------------------------------
# Email types
# ---------------------------------------------------------------------------

def send_verification_email(to_email: str, full_name: str, verify_url: str) -> None:
    """
    Send the email-verification link issued at registration.

    verify_url is the full URL: https://hermes.in/auth/verify-email?token=<token>
    """
    subject = "Verify your Hermes account"
    body = f"""Hi {full_name},

Welcome to Hermes — Government Job Notification Portal!

Please verify your email address by clicking the link below:

{verify_url}

This link expires in 24 hours.

If you did not create an account, please ignore this email.

— The Hermes Team
"""
    _send(to_email, subject, body)


def send_password_reset_email(to_email: str, full_name: str, reset_url: str) -> None:
    """
    Send the password-reset link generated by /api/v1/auth/forgot-password.

    reset_url is the full URL: https://hermes.in/auth/reset-password?token=<token>
    """
    subject = "Reset your Hermes password"
    body = f"""Hi {full_name},

We received a request to reset the password for your Hermes account.

Click the link below to set a new password:

{reset_url}

This link expires in 1 hour. If you did not request a password reset,
please ignore this email — your password will not change.

— The Hermes Team
"""
    _send(to_email, subject, body)


def send_welcome_email(to_email: str, full_name: str) -> None:
    """
    Confirmation email sent after the user verifies their email address.
    """
    subject = "Welcome to Hermes!"
    body = f"""Hi {full_name},

Your email has been verified successfully. Your Hermes account is now active.

You can now:
  • Browse the latest government job vacancies
  • Set up your profile for personalised notifications
  • Track application deadlines

Visit https://hermes.in to get started.

— The Hermes Team
"""
    _send(to_email, subject, body)


def send_job_notification_email(
    to_email: str,
    full_name: str,
    job_title: str,
    organization: str,
    application_end: str,
    job_url: str,
) -> None:
    """
    Notify a matched user about a new job vacancy.
    """
    subject = f"New Job Alert: {job_title} — {organization}"
    body = f"""Hi {full_name},

A new government job vacancy matching your profile is now available:

Job Title   : {job_title}
Organisation: {organization}
Last Date   : {application_end}

View full details and apply here:
{job_url}

Good luck!

— The Hermes Team

--
To manage your notification preferences, log in to your account at https://hermes.in
"""
    _send(to_email, subject, body)


def send_deadline_reminder_email(
    to_email: str,
    full_name: str,
    job_title: str,
    organization: str,
    days_left: int,
    application_end: str,
    job_url: str,
) -> None:
    """
    Reminder sent 7, 3, or 1 day(s) before an application deadline.
    """
    subject = f"Reminder: {days_left} day(s) left to apply — {job_title}"
    body = f"""Hi {full_name},

This is a reminder that the application deadline for the following job
is approaching:

Job Title   : {job_title}
Organisation: {organization}
Last Date   : {application_end}
Days Left   : {days_left}

Apply now:
{job_url}

Don't miss out!

— The Hermes Team
"""
    _send(to_email, subject, body)


# ---------------------------------------------------------------------------
# Private send helper
# ---------------------------------------------------------------------------

def _send(to_email: str, subject: str, body: str) -> None:
    """
    Construct a Message and send it via Flask-Mail.

    Raises exceptions from Flask-Mail / smtplib on failure.
    The caller (Celery task) is responsible for retry logic.
    """
    mail = get_mail()
    sender = current_app.config.get("MAIL_DEFAULT_SENDER") or current_app.config.get("MAIL_USERNAME")
    if not sender:
        raise RuntimeError("Email sender is not configured. Set MAIL_DEFAULT_SENDER or MAIL_USERNAME.")
    msg = Message(subject=subject, recipients=[to_email], body=body, sender=sender)
    mail.send(msg)
